FROM jenkins/ssh-agent:jdk17

USER root

RUN apt-get update && apt-get install -y lsb-release

#RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
#  https://download.docker.com/linux/debian/gpg

#RUN echo "deb [arch=$(dpkg --print-architecture) \
#  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#  https://download.docker.com/linux/debian \
#  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

RUN apt update && apt install tzdata python3 python3-pip python3-pytest python3-flask python3-flake8 python3-coverage wget -y

RUN wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz  && \
    tar -xzf apache-jmeter-5.6.3.tgz -C /opt/ && \
    ln -s /opt/apache-jmeter-5.6.3/bin/jmeter /usr/local/bin/jmeter && \
    rm apache-jmeter-5.6.3.tgz

RUN wget https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.10.0/wiremock-standalone-3.10.0.jar

RUN mkdir -p /home/jenkins/downloads/ && mv ./wiremock-standalone-3.10.0.jar downloads/wiremock-standalone-3.10.0.jar && \
    chmod +x /home/jenkins/downloads/wiremock-standalone-3.10.0.jar
 

RUN pip install --no-cache-dir bandit --break-system-packages

ENV JMETER_HOME=/opt/apache-jmeter-5.6.3

ENV TZ="America/Mazatlan"

USER jenkins
